### ISSUE TITLE
Syntax highlight doesn't work for every language

### ISSUE THREAD

**Issue by Krishath** [TowerofHanoi/towerofhanoi.github.io#12]
Working Python highlighter: http://toh.necst.it/plaidctf2015/forensics/PNG_Uncorrupt/
Not working PHP one: http://toh.necst.it/dctf2015/web/DCTF_2015_Web/

**Comment by pogliamarci** [comment]
As per the documentation (http://pygments.org/docs/lexers/), the highlighter requires php code to be wrapped inside the usual <?php ?> tags, unless the "startinline" option is passed to the highlighter.
