### ISSUE TITLE
RSS feeds don't work!

### ISSUE THREAD

**Issue by ocean1** [TowerofHanoi/towerofhanoi.github.io#5]
the feed is not a correct xml but looks like it has the same content of index.html.

part of the content:
```html
    <body>

    <nav id="my-menu">
  <div>
    <img src="/img/logo.png" class="about-image" height="30" width="30" alt="Tower of Hanoi Blog">
    <b>Tower of Hanoi</b>
    <ul class="pages">
```

**Comment by ocean1** [comment]
@Krishath have fun with jekyll and ruby :neckbeard:

**Comment by pogliamarci** [comment]
Jekyll was applying the default template event to the rss feed page.

@Krishath I noticed this yesterday but forgot to fix it
